### PR TITLE
Added use_vhost option to service

### PR DESCRIPTION
**Pull request by exadeci**

### CODE REVIEW

**Comment by arthurnn** [comment]
So, what would the option do if the is `false` ?

**Comment by exadeci** [comment]
https://github.com/exadeci/s3/commit/4cc2c6efef079e63b29bcbf2cbc5840b63f9b7c4#diff-629044b95d7d042962bb6f68a6188486R21
It would force to use subdiretories for buckets instead of vhost the same way it behaves without ssl or similar to https://github.com/aws/aws-sdk-ruby/blob/0d054b6eaaf6653210562e242a8586226565cbf4/aws-sdk-core/lib/aws-sdk-core/plugins/s3_bucket_dns.rb#L13

**Comment by arthurnn** [comment]
@exadeci make sense.. can you add a test case for this new option?
thanks

**Comment by exadeci** [comment]
So it seems that using a bucket as a path was already tested so I just added the option to force the vhost to false to it.

**Comment by arthurnn** [comment]
cool..
thanks

**Pull request merged**
